version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - add-ssh-keys:
        fingerprints:
          - "21:50:af:56:cb:8a:d8:22:27:90:6b:f2:8c:1f:23:8a"
      - run:
          name: check stuff
          command: |
            echo $SSH_USER
            echo $SSH_HOST
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o "StrictHostKeyChecking no" landes-hub.de@ssh.strato.de
            pwd
