version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - add-ssh-keys:
          fingerprints:
            - "21:50:af:56:cb:8a:d8:22:27:90:6b:f2:8c:1f:23:8a"
      - checkout
      - run: ls -al
      - run:
          name: Deploy Over SSH
          command: |
            scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v ./ landes-hub.de@ssh.strato.de:/sites/test/
            #ssh -o "StrictHostKeyChecking no" landes-hub.de@ssh.strato.de "pwd ; touch test.txt ;"
